import {
  FaFacebookF,
  FaTwitter,
  FaInstagram,
  FaLinkedinIn,
  FaMedium,
} from "react-icons/fa";

const SocialShare = [
  { Social: <FaFacebookF />, link: "https://www.facebook.com/tuhin96" },
  { Social: <FaTwitter />, link: "https://x.com/Its_Me_Ronnie_" },
  { Social: <FaInstagram />, link: "https://www.instagram.com/__horcrux._/" },
  { Social: <FaLinkedinIn />, link: "https://www.linkedin.com/in/tuhinmallick/" },
  { Social: <FaMedium />, link: "https://medium.com/@tuhin.mallick" },
];

/**
 * @description Generates HTML code for a website's footer, featuring social media
 * links and copyright information.
 * 
 * @returns {HTML element} a footer element with social sharing links and copyright
 * information.
 * 
 * 	* The `div.row` element contains a `div.col-md-6` element on either side.
 * 		+ The first `div.col-md-6` element contains a `nav` element with a
 * `justify-content-center` and `justify-content-md-start` classes. This nav element
 * contains a mapping of SocialShare objects, each represented by an anchor tag with
 * a key property. Each anchor tag has a href attribute set to the link property of
 * its corresponding SocialShare object, and a rel attribute set to "noreferrer" to
 * prevent annoying pop-ups.
 * 		+ The second `div.col-md-6` element contains a paragraph of text with a copyright
 * notice. The paragraph has an anchor tag with a href attribute set to the URL of
 * the ib-themes portfolio, and a rel attribute set to "noreferrer" for the same
 * reason as before.
 * 	* The `Footer` function does not include any personal pronouns (such as "I", "we",
 * or "our"), first-person statements (such as "hello" or "sure"), or repetition of
 * the question. It only uses neutral, passive voice language to explain the structure
 * and properties of the output returned by the function.
 */
const Footer = () => {
  return (
    <>
      <div className="row align-items-center">
        <div className="col-md-6 my-2">
          {/**
           * @description Generates high-quality documentation for given code.
           * 
           * @param {string} className - class name of the div element being generated by the
           */}
          <div className="nav justify-content-center justify-content-md-start">
            {SocialShare.map((val, i) => (
              <a key={i} href={`${val.link}`} rel="noreferrer" target="_blank">
                {val.Social}
              </a>
            ))}
          </div>
          {/* End .nav */}
        </div>
        {/* End .col */}

        <div className="col-md-6 my-2 text-center text-md-end">
          <p>
            © {new Date().getFullYear()} copyright{" "}
            <a
              href="https://themeforest.net/user/ib-themes/portfolio"
              target="_blank"
              rel="noreferrer"
            >
              ib-themes
            </a>{" "}
            all right reserved
          </p>
        </div>
        {/* End .col */}
      </div>
      {/* End .row */}
    </>
  );
};

export default Footer;
